### ISSUE TITLE
Don't automatically typecast numeric strings

### ISSUE THREAD

**Issue by therealgaxbo** [Crell/EnvMapper#3]
Strings like telephone numbers are numeric but should not be modelled as integers.  If there is a leading zero this will even cause data corruption.

Probably should only cast as needed to match the property type.

**Comment by kAlvaro** [comment]
To reproduce:

```ini
POSTAL_CODE='09001'
```

```php
class Example
{
    public readonly string $postalCode;
}
```

```php
$example = $mapper->map(Example::class);
```

> <b>Fatal error</b>:  Uncaught Crell\EnvMapper\TypeMismatch: Could not read environment variable for &quot;postalCode&quot; on Some\Namespace\Example.  A string was expected but int provided. in C:\...\vendor\crell\envmapper\src\TypeMismatch.php:15

**Comment by Crell** [comment]
Fixed in `master`.  The new approach is very slightly slower, but still acceptable, especially as it's more robust.  Thanks!
