### ISSUE TITLE
Default values that are falsy will not be set

### ISSUE THREAD

**Issue by SpadXIII** [Crell/EnvMapper#4]
I was just checking out this cool little thing and ran into a little issue: when you use falsy default values (empty string, zero, null, false) they won't get set. This is because `getDefaultValueFromConstructor` returns the actual value which is then implicitly checked in an if-statement.

A solution could be to extract that check into a `hasDefaultValueFromConstructor` method and let `getDefaultValueFromConstructor` only get the actual value.

**Comment by SpadXIII** [comment]
I'm out of time for today, so can't make an actual PR. I can make a PR in a few days though :)

**Comment by Crell** [comment]
Ah ha!  You are correct.  Good catch.  I'll wait for a PR, or until I am next bored and feel like fixing bugs. :smile:   Thanks.
